package eu.kanade.tachiyomi.animeextension.en.javfinder

internal fun getJavFinderCategory() = listOf<JavFinder.Type>(
    JavFinder.Type("Blowjob", "/category/blowjob"),
    JavFinder.Type("Creampie", "/category/creampie"),
    JavFinder.Type("Handjob", "/category/handjob"),
    JavFinder.Type("Cowgirl", "/category/cowgirl"),
    JavFinder.Type("Censored", "/category/censored"),
    JavFinder.Type("Beautiful Girl", "/category/beautiful-girl"),
    JavFinder.Type("Big tits", "/category/big-tits"),
    JavFinder.Type("Doggy Style", "/category/doggy-style"),
    JavFinder.Type("Doggystyle", "/category/doggystyle"),
    JavFinder.Type("Uncensored", "/category/uncensored"),
    JavFinder.Type("Cumshot", "/category/cumshot"),
    JavFinder.Type("Cunnilingus", "/category/cunnilingus"),
    JavFinder.Type("Asian", "/category/asian"),
    JavFinder.Type("Married Woman", "/category/married-woman"),
    JavFinder.Type("Japanese", "/category/japanese"),
    JavFinder.Type("HD Porn", "/category/hd-porn"),
    JavFinder.Type("Fingering", "/category/fingering"),
    JavFinder.Type("69 Style", "/category/69-style"),
    JavFinder.Type("Big Natural Tits", "/category/big-natural-tits"),
    JavFinder.Type("Hi-Def", "/category/hi-def"),
    JavFinder.Type("Deep Throat", "/category/deep-throat"),
    JavFinder.Type("Masturbation", "/category/masturbation"),
    JavFinder.Type("College", "/category/college"),
    JavFinder.Type("Shaved Pussy", "/category/shaved-pussy"),
    JavFinder.Type("Teen", "/category/teen"),
    JavFinder.Type("Solowork", "/category/solowork"),
    JavFinder.Type("Toys", "/category/toys"),
    JavFinder.Type("Featured Actress", "/category/featured-actress"),
    JavFinder.Type("Lingerie", "/category/lingerie"),
    JavFinder.Type("Mature", "/category/mature"),
    JavFinder.Type("Threesome", "/category/threesome"),
    JavFinder.Type("Titty Fuck", "/category/titty-fuck"),
    JavFinder.Type("Deep Throating", "/category/deep-throating"),
    JavFinder.Type("Mature Woman", "/category/mature-woman"),
    JavFinder.Type("Squirting", "/category/squirting"),
    JavFinder.Type("Uniform", "/category/uniform"),
    JavFinder.Type("Schoolgirl", "/category/schoolgirl"),
    JavFinder.Type("Big Tits Lover", "/category/big-tits-lover"),
    JavFinder.Type("Finger Fuck", "/category/finger-fuck"),
    JavFinder.Type("Blow", "/category/blow"),
    JavFinder.Type("Wife", "/category/wife"),
    JavFinder.Type("Tit fuck", "/category/tit-fuck"),
    JavFinder.Type("Family RolePlay Porn", "/category/family-roleplay-porn"),
    JavFinder.Type("Slut", "/category/slut"),
    JavFinder.Type("Older Sister", "/category/older-sister"),
    JavFinder.Type("Slender", "/category/slender"),
    JavFinder.Type("Facial", "/category/facial"),
    JavFinder.Type("POV", "/category/pov"),
    JavFinder.Type("Rape", "/category/rape"),
    JavFinder.Type("Digital Mosaic", "/category/digital-mosaic"),
    JavFinder.Type("School Girls", "/category/school-girls"),
    JavFinder.Type("Beautiful Tits", "/category/beautiful-tits"),
    JavFinder.Type("Milf", "/category/milf"),
    JavFinder.Type("Massage", "/category/massage"),
    JavFinder.Type("Cosplay", "/category/cosplay"),
    JavFinder.Type("Office lady", "/category/office-lady"),
    JavFinder.Type("Hardcore", "/category/hardcore"),
    JavFinder.Type("Sex Change/Female Transformation", "/category/sex-changefemale-transformation"),
    JavFinder.Type("Incest", "/category/incest"),
    JavFinder.Type("Ass", "/category/ass"),
    JavFinder.Type("Adultery", "/category/adultery"),
    JavFinder.Type("Voyeur", "/category/voyeur"),
    JavFinder.Type("School Uniform", "/category/school-uniform"),
    JavFinder.Type("Threesome / Foursome", "/category/threesome-foursome"),
    JavFinder.Type("Sex Toys", "/category/sex-toys"),
    JavFinder.Type("Over 4 Hours", "/category/over-4-hours"),
    JavFinder.Type("Anal", "/category/anal"),
    JavFinder.Type("Cuckold", "/category/cuckold"),
    JavFinder.Type("Nasty, Hardcore", "/category/nasty-hardcore"),
    JavFinder.Type("4HR+", "/category/4hr"),
    JavFinder.Type("Bukkake", "/category/bukkake"),
    JavFinder.Type("Drama", "/category/drama"),
    JavFinder.Type("Natural Tits", "/category/natural-tits"),
    JavFinder.Type("Gangbang", "/category/gangbang"),
    JavFinder.Type("Small Tits", "/category/small-tits"),
    JavFinder.Type("Gonzo", "/category/gonzo"),
    JavFinder.Type("Cheating Wife", "/category/cheating-wife"),
    JavFinder.Type("Lotion", "/category/lotion"),
    JavFinder.Type("Cum", "/category/cum"),
    JavFinder.Type("Compilation", "/category/compilation"),
    JavFinder.Type("Orgy", "/category/orgy"),
    JavFinder.Type("3P, 4P", "/category/3p-4p"),
    JavFinder.Type("Documentary", "/category/documentary"),
    JavFinder.Type("Nurse", "/category/nurse"),
    JavFinder.Type("BDSM", "/category/bdsm"),
    JavFinder.Type("Lesbians", "/category/lesbians"),
    JavFinder.Type("Outdoor", "/category/outdoor"),
    JavFinder.Type("Big Asses", "/category/big-asses"),
    JavFinder.Type("BBW", "/category/bbw"),
    JavFinder.Type("Hot Spring", "/category/hot-spring"),
    JavFinder.Type("Lesbian", "/category/lesbian"),
    JavFinder.Type("Nymphomaniac", "/category/nymphomaniac"),
    JavFinder.Type("Kimono", "/category/kimono"),
    JavFinder.Type("Daydreamers", "/category/daydreamers"),
    JavFinder.Type("Sister", "/category/sister"),
    JavFinder.Type("Breast Milk", "/category/breast-milk"),
    JavFinder.Type("Masturbate", "/category/masturbate"),
    JavFinder.Type("Stepfamily", "/category/stepfamily"),
    JavFinder.Type("Pretty Model", "/category/pretty-model"),
    JavFinder.Type("Cum Swallowing", "/category/cum-swallowing"),
    JavFinder.Type("Shaved", "/category/shaved"),
    JavFinder.Type("Best, Omnibus", "/category/best-omnibus"),
    JavFinder.Type("Fisting", "/category/fisting"),
    JavFinder.Type("Older & Younger Sist", "/category/older-younger-sist"),
    JavFinder.Type("Gal", "/category/gal"),
    JavFinder.Type("Teacher", "/category/teacher"),
    JavFinder.Type("Female College Student", "/category/female-college-student"),
    JavFinder.Type("Group sex", "/category/group-sex"),
    JavFinder.Type("Huge Butt", "/category/huge-butt"),
    JavFinder.Type("Female Teacher", "/category/female-teacher"),
    JavFinder.Type("Facials", "/category/facials"),
    JavFinder.Type("College Girl", "/category/college-girl"),
    JavFinder.Type("Anal Sex", "/category/anal-sex"),
    JavFinder.Type("Black Man", "/category/black-man"),
    JavFinder.Type("Breasts", "/category/breasts"),
    JavFinder.Type("Ass Lover", "/category/ass-lover"),
    JavFinder.Type("Debut", "/category/debut"),
    JavFinder.Type("Toy", "/category/toy"),
    JavFinder.Type("Foot Fetish", "/category/foot-fetish"),
    JavFinder.Type("Bikini", "/category/bikini"),
    JavFinder.Type("Affair", "/category/affair"),
    JavFinder.Type("Massage Parlor", "/category/massage-parlor"),
    JavFinder.Type("Shame", "/category/shame"),
    JavFinder.Type("Picking Up Girls", "/category/picking-up-girls"),
    JavFinder.Type("Couple", "/category/couple"),
    JavFinder.Type("Asian Actress", "/category/asian-actress"),
    JavFinder.Type("Urination", "/category/urination"),
    JavFinder.Type("Embarrassment", "/category/embarrassment"),
    JavFinder.Type("Hairy", "/category/hairy"),
    JavFinder.Type("Pantyhose", "/category/pantyhose"),
    JavFinder.Type("Maid/Meido", "/category/maid-meido"),
    JavFinder.Type("Dirty Talk", "/category/dirty-talk"),
    JavFinder.Type("Hard Sex", "/category/hard-sex"),
    JavFinder.Type("Young Wife", "/category/young-wife"),
    JavFinder.Type("Debut Production", "/category/debut-production"),
    JavFinder.Type("Abuse", "/category/abuse"),
    JavFinder.Type("Kiss", "/category/kiss"),
    JavFinder.Type("Kiss Kiss", "/category/kiss-kiss"),
    JavFinder.Type("Butt", "/category/butt"),
    JavFinder.Type("Cherry Boy", "/category/cherry-boy"),
    JavFinder.Type("Bathroom", "/category/bathroom"),
    JavFinder.Type("Chubby", "/category/chubby"),
    JavFinder.Type("Beauty Shop", "/category/beauty-shop"),
    JavFinder.Type("Face Sitting", "/category/face-sitting"),
    JavFinder.Type("Humiliation", "/category/humiliation"),
    JavFinder.Type("OL", "/category/ol"),
    JavFinder.Type("Torture", "/category/torture"),
    JavFinder.Type("Other Fetishes", "/category/other-fetishes"),
    JavFinder.Type("Nampa", "/category/nampa"),
    JavFinder.Type("Variety", "/category/variety"),
    JavFinder.Type("Bondage", "/category/bondage"),
    JavFinder.Type("Other Fetish", "/category/other-fetish"),
    JavFinder.Type("Secretary", "/category/secretary"),
    JavFinder.Type("Swingers", "/category/swingers"),
    JavFinder.Type("Minimal Mosaic", "/category/minimal-mosaic"),
    JavFinder.Type("Maid", "/category/maid"),
    JavFinder.Type("Ropes & Ties", "/category/ropes-ties"),
    JavFinder.Type("Subjectivity", "/category/subjectivity"),
    JavFinder.Type("Restraint", "/category/restraint"),
    JavFinder.Type("Dirty Words", "/category/dirty-words"),
    JavFinder.Type("Anal Play", "/category/anal-play"),
    JavFinder.Type("Youthful", "/category/youthful"),
    JavFinder.Type("Entertainer", "/category/entertainer"),
    JavFinder.Type("Club Hostess & Sex Worker", "/category/club-hostess-sex-worker"),
    JavFinder.Type("Electric Massager", "/category/electric-massager"),
    JavFinder.Type("Outdoors", "/category/outdoors"),
    JavFinder.Type("Image Video", "/category/image-video"),
    JavFinder.Type("Stepmom", "/category/stepmom"),
    JavFinder.Type("Risky Mosaic", "/category/risky-mosaic"),
    JavFinder.Type("Underwear", "/category/underwear"),
    JavFinder.Type("Sports", "/category/sports"),
    JavFinder.Type("Tits", "/category/tits"),
    JavFinder.Type("Transsexual", "/category/transsexual"),
    JavFinder.Type("Submissive Men", "/category/submissive-men"),
    JavFinder.Type("Molester", "/category/molester"),
    JavFinder.Type("Various Worker", "/category/various-worker"),
    JavFinder.Type("Glasses", "/category/glasses"),
    JavFinder.Type("School", "/category/school"),
    JavFinder.Type("Solo Girl", "/category/solo-girl"),
    JavFinder.Type("Sweat", "/category/sweat"),
    JavFinder.Type("Big Vibrator", "/category/big-vibrator"),
    JavFinder.Type("Prostitutes", "/category/prostitutes"),
    JavFinder.Type("Pregnant", "/category/pregnant"),
    JavFinder.Type("Shotacon", "/category/shotacon"),
    JavFinder.Type("Sweating", "/category/sweating"),
    JavFinder.Type("Promiscuity", "/category/promiscuity"),
    JavFinder.Type("Masochist Man", "/category/masochist-man"),
    JavFinder.Type("69", "/category/69"),
    JavFinder.Type("SM", "/category/sm"),
    JavFinder.Type("Sleeping", "/category/sleeping"),
    JavFinder.Type("Huge Cock", "/category/huge-cock"),
    JavFinder.Type("Mother", "/category/mother"),
    JavFinder.Type("Footjob", "/category/footjob"),
    JavFinder.Type("Employee/Coworker", "/category/employeecoworker"),
    JavFinder.Type("Actress Best Compilation", "/category/actress-best-compilation"),
    JavFinder.Type("Evil", "/category/evil"),
    JavFinder.Type("Foot Job/Ashifechi", "/category/foot-job-ashifechi"),
    JavFinder.Type("Bride, Young Wife", "/category/bride-young-wife"),
    JavFinder.Type("Girl", "/category/girl"),
    JavFinder.Type("Panty Shot", "/category/panty-shot"),
    JavFinder.Type("Idol & Celebrity", "/category/idol-celebrity"),
    JavFinder.Type("Acme · Orgasm", "/category/acme-orgasm"),
    JavFinder.Type("Swimsuits", "/category/swimsuits"),
    JavFinder.Type("Bitch", "/category/bitch"),
    JavFinder.Type("Blu-ray", "/category/blu-ray"),
    JavFinder.Type("Virgin Man", "/category/virgin-man"),
    JavFinder.Type("Confinement", "/category/confinement"),
    JavFinder.Type("Female Boss", "/category/female-boss"),
    JavFinder.Type("Huge Dick - Large Dick", "/category/huge-dick-large-dick"),
    JavFinder.Type("Swimsuit", "/category/swimsuit"),
    JavFinder.Type("Quickie", "/category/quickie"),
    JavFinder.Type("Big Nipples", "/category/big-nipples"),
    JavFinder.Type("Tall Girl", "/category/tall-girl"),
    JavFinder.Type("S********l", "/category/sl"),
    JavFinder.Type("Swallow", "/category/swallow"),
    JavFinder.Type("Emmanuel", "/category/emmanuel"),
    JavFinder.Type("Bath", "/category/bath"),
    JavFinder.Type("Various Professions", "/category/various-professions"),
    JavFinder.Type("Stepmother", "/category/stepmother"),
    JavFinder.Type("Restraints", "/category/restraints"),
    JavFinder.Type("Busty Fetish", "/category/busty-fetish"),
    JavFinder.Type("Enema", "/category/enema"),
    JavFinder.Type("Step Mom Step Son Porn", "/category/step-mom-step-son-porn"),
    JavFinder.Type("Ultra-Huge Tits", "/category/ultra-huge-tits"),
    JavFinder.Type("Mini", "/category/mini"),
    JavFinder.Type("English Subbed JAV", "/category/english-subbed-jav"),
    JavFinder.Type("Tall", "/category/tall"),
    JavFinder.Type("Planning", "/category/planning"),
    JavFinder.Type("Fighting Action", "/category/fighting-action"),
    JavFinder.Type("Cross Dresser", "/category/cross-dresser"),
    JavFinder.Type("Leg Fetish", "/category/leg-fetish"),
    JavFinder.Type("Lesbian Kissing", "/category/lesbian-kissing"),
    JavFinder.Type("Facesitting", "/category/facesitting"),
    JavFinder.Type("Public Place", "/category/public-place"),
    JavFinder.Type("Idol Video", "/category/idol-video"),
    JavFinder.Type("Anchorwoman", "/category/anchorwoman"),
    JavFinder.Type("SOD / Big Tits / Fetishes SALE", "/category/sod-big-tits-fetishes-sale"),
    JavFinder.Type("Special Effects", "/category/special-effects"),
    JavFinder.Type("Lesbian Kiss", "/category/lesbian-kiss"),
    JavFinder.Type("Titty Shots", "/category/titty-shots"),
    JavFinder.Type("Short & Petite", "/category/short-petite"),
    JavFinder.Type("Korean", "/category/korean"),
    JavFinder.Type("Bloomers", "/category/bloomers"),
    JavFinder.Type("Shemale", "/category/shemale"),
    JavFinder.Type("Sexy", "/category/sexy"),
    JavFinder.Type("Submissive Woman", "/category/submissive-woman"),
    JavFinder.Type("Close Up", "/category/close-up"),
    JavFinder.Type("Pranks", "/category/pranks"),
    JavFinder.Type("Petite", "/category/petite"),
    JavFinder.Type("Love", "/category/love"),
    JavFinder.Type("Cross Dressing", "/category/cross-dressing"),
    JavFinder.Type("School Swimsuits", "/category/school-swimsuits"),
    JavFinder.Type("More Than 16 Hours Of Footage", "/category/more-than-16-hours-of-footage"),
    JavFinder.Type("Sailor Uniform", "/category/sailor-uniform"),
    JavFinder.Type("School Swimsuit", "/category/school-swimsuit"),
    JavFinder.Type("Harem", "/category/harem"),
    JavFinder.Type("Housewife", "/category/housewife"),
    JavFinder.Type("Drug", "/category/drug"),
    JavFinder.Type("Mini Skirt", "/category/mini-skirt"),
    JavFinder.Type("Sadism", "/category/sadism"),
    JavFinder.Type("Subordinates / Colleagues", "/category/subordinates-colleagues"),
    JavFinder.Type("Soapland", "/category/soapland"),
    JavFinder.Type("Genital Close-Up", "/category/genital-close-up"),
    JavFinder.Type("Vibrator", "/category/vibrator"),
    JavFinder.Type("Close Up/Pussy", "/category/close-up-pussy"),
    JavFinder.Type("Vibe", "/category/vibe"),
    JavFinder.Type("Car", "/category/car"),
    JavFinder.Type("Miniskirt", "/category/miniskirt"),
    JavFinder.Type("Bunny Girl", "/category/bunny-girl"),
    JavFinder.Type("Substance Use", "/category/substance-use"),
    JavFinder.Type("Huge Tits", "/category/huge-tits"),
    JavFinder.Type("Original Collaboration", "/category/original-collaboration"),
    JavFinder.Type("Funny", "/category/funny"),
    JavFinder.Type("Gym Clothes", "/category/gym-clothes"),
    JavFinder.Type("No Bra", "/category/no-bra"),
    JavFinder.Type("Homemade", "/category/homemade"),
    JavFinder.Type("Sailor Suit", "/category/sailor-suit"),
    JavFinder.Type("Impromptu Sex", "/category/impromptu-sex"),
    JavFinder.Type("Caucasian Actress", "/category/caucasian-actress"),
    JavFinder.Type("Kimono, Mourning", "/category/kimono-mourning"),
    JavFinder.Type("Virgin", "/category/virgin"),
    JavFinder.Type("Femdom", "/category/femdom"),
    JavFinder.Type("Panties", "/category/panties"),
    JavFinder.Type("Childhood Friend", "/category/childhood-friend"),
    JavFinder.Type(" Male Squirting", "/category/male-squirting"),
    JavFinder.Type("Skinny", "/category/skinny"),
    JavFinder.Type("Conceived", "/category/conceived"),
    JavFinder.Type("Bus Guide", "/category/bus-guide"),
    JavFinder.Type("User Submission", "/category/user-submission"),
    JavFinder.Type("Prank", "/category/prank"),
    JavFinder.Type("Black Actor", "/category/black-actor"),
    JavFinder.Type("Series", "/category/series"),
    JavFinder.Type("Female Doctor", "/category/female-doctor"),
    JavFinder.Type("Orgasm", "/category/orgasm"),
    JavFinder.Type("Soapland Girl", "/category/soapland-girl"),
    JavFinder.Type("Erotic Wear", "/category/erotic-wear"),
    JavFinder.Type("Stewardess", "/category/stewardess"),
    JavFinder.Type("Coprophagy", "/category/coprophagy"),
    JavFinder.Type("Back", "/category/back"),
    JavFinder.Type("Date", "/category/date"),
    JavFinder.Type("Porn", "/category/porn"),
    JavFinder.Type("Multiple Story", "/category/multiple-story"),
    JavFinder.Type("Adopted Daughter", "/category/adopted-daughter"),
    JavFinder.Type("Widow", "/category/widow"),
    JavFinder.Type("Female Detective", "/category/female-detective"),
    JavFinder.Type("Old Playmates", "/category/old-playmates"),
    JavFinder.Type("Car Sex", "/category/car-sex"),
    JavFinder.Type("M-jo", "/category/m-jo"),
    JavFinder.Type("Hotel", "/category/hotel"),
    JavFinder.Type("Female Investigator", "/category/female-investigator"),
    JavFinder.Type("FANZA Exclusive", "/category/fanza-exclusive"),
    JavFinder.Type("Fan Appreciation", "/category/fan-appreciation"),
    JavFinder.Type("4K", "/category/4k"),
    JavFinder.Type("Golden Shower", "/category/golden-shower"),
    JavFinder.Type("Fan Appreciation/ Home Visit", "/category/fan-appreciation-home-visit"),
    JavFinder.Type("Travel", "/category/travel"),
    JavFinder.Type("Hidden Cams", "/category/hidden-cams"),
    JavFinder.Type("Private Tutor", "/category/private-tutor"),
    JavFinder.Type("Suntan", "/category/suntan"),
    JavFinder.Type("Fantasy", "/category/fantasy"),
    JavFinder.Type("Daydream", "/category/daydream"),
    JavFinder.Type("AV Actress", "/category/av-actress"),
    JavFinder.Type("VENUS / Prestige / Dogma SALE", "/category/venus-prestige-dogma-sale"),
    JavFinder.Type("Non-nude Erotica", "/category/non-nude-erotica"),
    JavFinder.Type("High-Quality VR", "/category/high-quality-vr"),
    JavFinder.Type("Spanking", "/category/spanking"),
    JavFinder.Type("Sun tan", "/category/sun-tan"),
    JavFinder.Type("Princess & Mademoiselle", "/category/princess-mademoiselle"),
    JavFinder.Type("Premature Ejaculation", "/category/premature-ejaculation"),
    JavFinder.Type("Masturbation Support", "/category/masturbation-support"),
    JavFinder.Type("TSUNDERE", "/category/tsundere"),
    JavFinder.Type("Scatology", "/category/scatology"),
    JavFinder.Type("VR Exclusive", "/category/vr-exclusive"),
    JavFinder.Type("Piss Drinking", "/category/piss-drinking"),
    JavFinder.Type("Swallowing", "/category/swallowing"),
    JavFinder.Type("Trip", "/category/trip"),
    JavFinder.Type("Drinking Party", "/category/drinking-party"),
    JavFinder.Type("Dildo", "/category/dildo"),
    JavFinder.Type("Best New Actress SALE 2", "/category/best-new-actress-sale-2"),
    JavFinder.Type("Shibari", "/category/shibari"),
    JavFinder.Type("Tutor", "/category/tutor"),
    JavFinder.Type("Model", "/category/model"),
    JavFinder.Type("Action", "/category/action"),
    JavFinder.Type("Upskirts", "/category/upskirts"),
    JavFinder.Type("Defecation", "/category/defecation"),
    JavFinder.Type("Female Warrior", "/category/female-warrior"),
    JavFinder.Type("School Stuff", "/category/school-stuff"),
    JavFinder.Type("Sport", "/category/sport"),
    JavFinder.Type("Egg Vibrator", "/category/egg-vibrator"),
    JavFinder.Type("Athlete", "/category/athlete"),
    JavFinder.Type("CASANOVA / Glory Quest / Prestige SALE", "/category/casanova-glory-quest-prestige-sale"),
    JavFinder.Type("Redhead", "/category/redhead"),
    JavFinder.Type("Race Queen", "/category/race-queen"),
    JavFinder.Type("Transformed Heroine", "/category/transformed-heroine"),
    JavFinder.Type("Straight", "/category/straight"),
    JavFinder.Type("Reversed Role", "/category/reversed-role"),
    JavFinder.Type("Aunt", "/category/aunt"),
    JavFinder.Type("Gag · Comedy", "/category/gag-comedy"),
    JavFinder.Type("Leotards", "/category/leotards"),
    JavFinder.Type("Business Attire", "/category/business-attire"),
    JavFinder.Type("Old Man", "/category/old-man"),
    JavFinder.Type("Bride", "/category/bride"),
    JavFinder.Type("Vomit", "/category/vomit"),
    JavFinder.Type("White Actress", "/category/white-actress"),
    JavFinder.Type("Softcore", "/category/softcore"),
    JavFinder.Type("Momotaro Eizo / Deeps / Plum SALE", "/category/momotaro-eizo-deeps-plum-sale"),
    JavFinder.Type("Instructor", "/category/instructor"),
    JavFinder.Type("G-Spot", "/category/g-spot"),
    JavFinder.Type("Hypnosis", "/category/hypnosis"),
    JavFinder.Type("Elder Male", "/category/elder-male"),
    JavFinder.Type("Foreign Objects", "/category/foreign-objects"),
    JavFinder.Type("For Women", "/category/for-women"),
    JavFinder.Type("Fake Tits", "/category/fake-tits"),
    JavFinder.Type("Object Insertion", "/category/object-insertion"),
    JavFinder.Type("CFNM", "/category/cfnm"),
    JavFinder.Type("Delusion", "/category/delusion"),
    JavFinder.Type("Dance", "/category/dance"),
    JavFinder.Type("Dogma / SOD / FA Pro /Prestige SALE", "/category/dogma-sod-fa-pro-prestige-sale"),
    JavFinder.Type("Oversea Import", "/category/oversea-import"),
    JavFinder.Type("Couple Swapping", "/category/couple-swapping"),
    JavFinder.Type("Cat Cosplay", "/category/cat-cosplay"),
    JavFinder.Type("Domination", "/category/domination"),
    JavFinder.Type("Flexible body", "/category/flexible-body"),
    JavFinder.Type("Leotard", "/category/leotard"),
    JavFinder.Type("Club Activities / Manager", "/category/club-activities-manager"),
    JavFinder.Type("Martial Arts", "/category/martial-arts"),
    JavFinder.Type("Loose Socks", "/category/loose-socks"),
    JavFinder.Type("Rolling Back Eyes / Fainting", "/category/rolling-back-eyes-fainting"),
    JavFinder.Type("Breast Peeker", "/category/breast-peeker"),
    JavFinder.Type("Landlady, Hostess", "/category/landlady-hostess"),
    JavFinder.Type("Other Asian", "/category/other-asian"),
    JavFinder.Type("Foreign Imports", "/category/foreign-imports"),
    JavFinder.Type("Female Anchor", "/category/female-anchor"),
    JavFinder.Type("Miss", "/category/miss"),
    JavFinder.Type("Knee-High Socks", "/category/knee-high-socks"),
    JavFinder.Type("Hospital / Clinic", "/category/hospital-clinic"),
    JavFinder.Type("Hot Springs", "/category/hot-springs"),
    JavFinder.Type("Cervix", "/category/cervix"),
    JavFinder.Type("Interracial", "/category/interracial"),
    JavFinder.Type("Auntie", "/category/auntie"),
    JavFinder.Type("No Undies", "/category/no-undies"),
    JavFinder.Type("Rimming", "/category/rimming"),
    JavFinder.Type("Muscular", "/category/muscular"),
    JavFinder.Type("SOD / Prestige / Ruby / Mousouzoku SALE", "/category/sod-prestige-ruby-mousouzoku-sale"),
    JavFinder.Type("Reverse Pick Up", "/category/reverse-pick-up"),
    JavFinder.Type("Dogma / SOD / Emmanuellle / Prestige SALE", "/category/dogma-sod-emmanuellle-prestige-sale"),
    JavFinder.Type("Granny", "/category/granny"),
    JavFinder.Type("Nose Fuck", "/category/nose-fuck"),
    JavFinder.Type("Cruel Expression", "/category/cruel-expression"),
    JavFinder.Type("Mistress", "/category/mistress"),
    JavFinder.Type("Reprinted Edition", "/category/reprinted-edition"),
    JavFinder.Type("Dark System", "/category/dark-system"),
    JavFinder.Type("Medical", "/category/medical"),
    JavFinder.Type("Hospital/Clinic", "/category/hospitalclinic"),
    JavFinder.Type("Action & Fighting", "/category/action-fighting"),
    JavFinder.Type("Flexible", "/category/flexible"),
    JavFinder.Type("Catgirl", "/category/catgirl"),
    JavFinder.Type("Girl Cosplay", "/category/girl-cosplay"),
    JavFinder.Type("Business Suit", "/category/business-suit"),
    JavFinder.Type("Naked Apron", "/category/naked-apron"),
    JavFinder.Type("Mensetsu", "/category/mensetsu"),
    JavFinder.Type("Anime Characters", "/category/anime-characters"),
    JavFinder.Type("Actress Best", "/category/actress-best"),
    JavFinder.Type("No Panties", "/category/no-panties"),
    JavFinder.Type("Interview", "/category/interview"),
    JavFinder.Type("Live Game Filming Edition", "/category/live-game-filming-edition"),
    JavFinder.Type("Gay", "/category/gay"),
    JavFinder.Type("Doll", "/category/doll"),
    JavFinder.Type("Tickling", "/category/tickling"),
    JavFinder.Type("OFFICE K’S / SOD SALE", "/category/office-ks-sod-sale"),
    JavFinder.Type("Nose Hook", "/category/nose-hook"),
    JavFinder.Type("How To", "/category/how-to"),
    JavFinder.Type("Pregnant Woman", "/category/pregnant-woman"),
    JavFinder.Type("Body Conscious", "/category/body-conscious"),
    JavFinder.Type("Training", "/category/training"),
    JavFinder.Type("Sex Conversion / Feminized", "/category/sex-conversion-feminized"),
    JavFinder.Type("Campaign Girl", "/category/campaign-girl"),
    JavFinder.Type("Mom Friends", "/category/mom-friends"),
    JavFinder.Type("Tight Dress", "/category/tight-dress"),
    JavFinder.Type("Waitress", "/category/waitress"),
    JavFinder.Type("Club Manager", "/category/club-manager"),
    JavFinder.Type("Knee Socks", "/category/knee-socks"),
    JavFinder.Type("Special 8 studios SALE", "/category/special-8-studios-sale"),
    JavFinder.Type("Time Stop", "/category/time-stop"),
    JavFinder.Type("Triple Happy SALE 3", "/category/triple-happy-sale-3"),
    JavFinder.Type("VR", "/category/vr"),
    JavFinder.Type("Muscle", "/category/muscle"),
    JavFinder.Type("Futanari", "/category/futanari"),
    JavFinder.Type("Magic Gal", "/category/magic-gal"),
    JavFinder.Type("Time Warp", "/category/time-warp"),
    JavFinder.Type("Yoga", "/category/yoga"),
    JavFinder.Type("Female Ninja", "/category/female-ninja"),
    JavFinder.Type("Spring festival SALE", "/category/spring-festival-sale"),
    JavFinder.Type("Historical Play", "/category/historical-play"),
    JavFinder.Type("Tentacle", "/category/tentacle"),
    JavFinder.Type("Booth Girl", "/category/booth-girl"),
    JavFinder.Type("Strapon", "/category/strapon"),
    JavFinder.Type("Receptionist", "/category/receptionist"),
    JavFinder.Type("Collaborative Work", "/category/collaborative-work"),
    JavFinder.Type("Queen", "/category/queen"),
    JavFinder.Type("Neglect", "/category/neglect"),
    JavFinder.Type("Prestige / Toyohiko / Jukujo JAPAN SALE", "/category/prestige-toyohiko-jukujo-japan-sale"),
    JavFinder.Type("Cosplay Costumes", "/category/cosplay-costumes"),
    JavFinder.Type("Striptease", "/category/striptease"),
    JavFinder.Type("Special 7 studios SALE", "/category/special-7-studios-sale"),
    JavFinder.Type("Masked", "/category/masked"),
    JavFinder.Type("Fighters", "/category/fighters"),
    JavFinder.Type("Chinese Dress", "/category/chinese-dress"),
    JavFinder.Type("Prestige / Mousouzoku / SOD SALE", "/category/prestige-mousouzoku-sod-sale"),
    JavFinder.Type("AV OPEN 2016 Planning Dept.", "/category/av-open-2016-planning-dept"),
    JavFinder.Type("Latex", "/category/latex"),
    JavFinder.Type("Serious", "/category/serious"),
    JavFinder.Type("Eyes-Roll-Back, Fainting", "/category/eyes-roll-back-fainting"),
    JavFinder.Type("D***king Party/Mixer", "/category/dking-partymixer"),
    JavFinder.Type("Pooping", "/category/pooping"),
    JavFinder.Type("S-Cute / Prestige / Gogos SALE", "/category/s-cute-prestige-gogos-sale"),
    JavFinder.Type("Otaku", "/category/otaku"),
    JavFinder.Type("Candle", "/category/candle"),
    JavFinder.Type("Long Boots", "/category/long-boots"),
    JavFinder.Type("Hermaphrodite", "/category/hermaphrodite"),
    JavFinder.Type("Exposure", "/category/exposure"),
    JavFinder.Type("Cheerleader", "/category/cheerleader"),
    JavFinder.Type("Comedy", "/category/comedy"),
    JavFinder.Type("Emmanuelle / Prestige / Mousouzoku SALE", "/category/emmanuelle-prestige-mousouzoku-sale"),
    JavFinder.Type("Brand Store SALE", "/category/brand-store-sale"),
    JavFinder.Type("Eros company", "/category/eros-company"),
    JavFinder.Type("Natural High / Prestige / Momotaro Eizo SALE", "/category/natural-high-prestige-momotaro-eizo-sale"),
    JavFinder.Type("Alice JAPAN / Max A / SOD SALE", "/category/alice-japan-max-a-sod-sale"),
    JavFinder.Type("Companion", "/category/companion"),
    JavFinder.Type("Speculum", "/category/speculum"),
    JavFinder.Type("Reserved Role", "/category/reserved-role"),
    JavFinder.Type("BBB / Celeb no Tomo / Milu SALE", "/category/bbb-celeb-no-tomo-milu-sale"),
    JavFinder.Type("Prestige / Dream Ticket / BabyEntertainment SALE", "/category/prestige-dream-ticket-babyentertainment-sale"),
    JavFinder.Type("LUNATICS / S-Cute / Emmanuelle SALE", "/category/lunatics-s-cute-emmanuelle-sale"),
    JavFinder.Type("Planet Plus / Ruby / Gogos SALE", "/category/planet-plus-ruby-gogos-sale"),
    JavFinder.Type("Old Lady", "/category/old-lady"),
    JavFinder.Type("Princess", "/category/princess"),
    JavFinder.Type("Nude", "/category/nude"),
    JavFinder.Type("StaffPicks06", "/category/staffpicks06"),
    JavFinder.Type("StaffPicks03", "/category/staffpicks03"),
    JavFinder.Type("SF", "/category/sf"),
    JavFinder.Type("Mask", "/category/mask"),
    JavFinder.Type("Celeb", "/category/celeb"),
    JavFinder.Type("Candle Drippings", "/category/candle-drippings"),
    JavFinder.Type("Confessional", "/category/confessional"),
    JavFinder.Type("Celeb no Tomo / Koala VR SALE", "/category/celeb-no-tomo-koala-vr-sale"),
    JavFinder.Type("Celebrity", "/category/celebrity"),
    JavFinder.Type("Alice JAPAN / Mousouzoku SALE", "/category/alice-japan-mousouzoku-sale"),
    JavFinder.Type("Cheongsam", "/category/cheongsam"),
    JavFinder.Type("Slave", "/category/slave"),
    JavFinder.Type("Priestess", "/category/priestess"),
    JavFinder.Type("Sci-Fi", "/category/sci-fi"),
    JavFinder.Type("Female Soldier", "/category/female-soldier"),
    JavFinder.Type("Lookalike", "/category/lookalike"),
    JavFinder.Type("Set Items", "/category/set-items"),
    JavFinder.Type("Triple Attack Happy SALE", "/category/triple-attack-happy-sale"),
    JavFinder.Type("Daughter", "/category/daughter"),
    JavFinder.Type("Crystal Eizo / SOD SALE", "/category/crystal-eizo-sod-sale"),
    JavFinder.Type("Experience Confession", "/category/experience-confession"),
    JavFinder.Type("Insult", "/category/insult"),
    JavFinder.Type("Hostess", "/category/hostess"),
    JavFinder.Type("Gyno Exam", "/category/gyno-exam"),
    JavFinder.Type("S**tology", "/category/stology"),
    JavFinder.Type("Best Actresses SALE", "/category/best-actresses-sale"),
    JavFinder.Type("Summer Sale 50% OFF", "/category/summer-sale-50-off"),
    JavFinder.Type("Prestige / Hot Entertainment / SOD / Nagae Style / SMS SALE", "/category/prestige-hot-entertainment-sod-nagae-style-sms-sale"),
    JavFinder.Type("Deeps / SOD / Prestige SALE", "/category/deeps-sod-prestige-sale"),
    JavFinder.Type("VENUS / SOD / Mousouzoku SALE", "/category/venus-sod-mousouzoku-sale"),
    JavFinder.Type("Romantic Comedy", "/category/romantic-comedy"),
    JavFinder.Type("Karma / KMP SALE", "/category/karma-kmp-sale"),
    JavFinder.Type("Hostesses", "/category/hostesses"),
    JavFinder.Type("Mini Skirt Police", "/category/mini-skirt-police"),
    JavFinder.Type("Horror", "/category/horror"),
    JavFinder.Type("SMS / Toyohiko / Prestige SALE", "/category/sms-toyohiko-prestige-sale"),
    JavFinder.Type("SOD / Prestige / BBB SALE", "/category/sod-prestige-bbb-sale"),
    JavFinder.Type("Bus Tour Guide", "/category/bus-tour-guide"),
    JavFinder.Type("FA Pro / SOD / Prestige / VENUS SALE", "/category/fa-pro-sod-prestige-venus-sale"),
    JavFinder.Type("BL", "/category/bl"),
    JavFinder.Type("Triple Happy SALE 2", "/category/triple-happy-sale-2"),
    JavFinder.Type("Dead Drunk", "/category/dead-drunk"),
    JavFinder.Type("Look-alike", "/category/look-alike"),
    JavFinder.Type("Prestige / Mellow Moon / Mature Woman SALE", "/category/prestige-mellow-moon-mature-woman-sale"),
    JavFinder.Type("Momotaro Eizo / CASANOVA / Prestige SALE", "/category/momotaro-eizo-casanova-prestige-sale"),
    JavFinder.Type("MAX-A / SOD / Prestige / BBB SALE", "/category/max-a-sod-prestige-bbb-sale"),
    JavFinder.Type("StaffPicks04", "/category/staffpicks04"),
    JavFinder.Type("Others", "/category/others"),
    JavFinder.Type("Best New Actress SALE", "/category/best-new-actress-sale"),
    JavFinder.Type("AV OPEN 2014 Heavyweight", "/category/av-open-2014-heavyweight"),
    JavFinder.Type("2020 Winter SALE 3", "/category/2020-winter-sale-3"),
    JavFinder.Type("Yukata", "/category/yukata"),
    JavFinder.Type("Peeping", "/category/peeping"),
    JavFinder.Type("AV OPEN 2015 Planning Dept.", "/category/av-open-2015-planning-dept"),
    JavFinder.Type("StaffPicks05", "/category/staffpicks05"),
    JavFinder.Type("VENUS / SOD / Prestige / Waap Entertainment SALE", "/category/venus-sod-prestige-waap-entertainment-sale"),
    JavFinder.Type("Sale (limited time)", "/category/sale-limited-time"),
    JavFinder.Type("Shokushu", "/category/shokushu"),
    JavFinder.Type("Special 13 studios SALE", "/category/special-13-studios-sale"),
    JavFinder.Type("A***e", "/category/ae"),
    JavFinder.Type("SOD / Aurora Project ANNEX / BabyEntertainment SALE", "/category/sod-aurora-project-annex-babyentertainment-sale"),
    JavFinder.Type("Miniskirt Police", "/category/miniskirt-police"),
    JavFinder.Type("Prestige / Alice JAPAN / KMP SALE", "/category/prestige-alice-japan-kmp-sale"),
    JavFinder.Type("SOD / Celeb no Tomo / LUNATICS SALE", "/category/sod-celeb-no-tomo-lunatics-sale"),
    JavFinder.Type("Kana Momonogi 5Th Anniversary SALE 3", "/category/kana-momonogi-5th-anniversary-sale-3"),
    JavFinder.Type("Aurora Project ANNEX / SOD / Prestige SALE", "/category/aurora-project-annex-sod-prestige-sale"),
    JavFinder.Type("Independent", "/category/independent"),
    JavFinder.Type("S1 NO.1 STYLE SALE", "/category/s1-no1-style-sale"),
    JavFinder.Type("S1 NO.1 STYLE SALE 3", "/category/s1-no1-style-sale-3"),
    JavFinder.Type("AV OPEN 2016 Hardcore Division", "/category/av-open-2016-hardcore-division"),
    JavFinder.Type("Psycho Thriller", "/category/psycho-thriller"),
    JavFinder.Type("Mixed Porn", "/category/mixed-porn"),
)
